databases:
  - name: fspSpotify
    user: fspSpotify
    plan: free
    region: ohio

services:
  - type: web
    name: fspSpotify
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fspSpotify
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
